version: '3.3'

services:
  cubitwelve-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      # You can use whatever password you like
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - cubitwelve-db:/var/lib/mysql
# Names our volume
volumes:
  cubitwelve-db: